import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import manifest from "@/app/manifest";

const root = process.cwd();
const sw = readFileSync(join(root, "public/sw.js"), "utf8");

describe("web app manifest", () => {
  const m = manifest();

  it("carries what a browser needs to offer installation", () => {
    expect(m.name).toBeTruthy();
    expect(m.short_name).toBeTruthy();
    expect(m.start_url).toBe("/");
    expect(m.display).toBe("standalone");
  });

  it("ships the icon sizes installability depends on", () => {
    const sizes = (m.icons ?? []).map((icon) => icon.sizes);
    expect(sizes).toContain("192x192");
    expect(sizes).toContain("512x512");
  });

  it("ships a maskable icon so the mark is not cropped into", () => {
    expect((m.icons ?? []).some((icon) => icon.purpose === "maskable")).toBe(true);
  });

  it("points every icon at a file that exists", () => {
    for (const icon of m.icons ?? []) {
      expect(existsSync(join(root, "public", icon.src)), `missing ${icon.src}`).toBe(true);
    }
  });
});

describe("service worker", () => {
  it("precaches routes that the app actually serves", () => {
    const routes: string[] = JSON.parse(sw.match(/const CORE_ROUTES = (\[[^\]]*\])/)![1]!.replace(/'/g, '"'));
    for (const route of routes) {
      const dir = route === "/" ? "src/app" : join("src/app", route);
      expect(existsSync(join(root, dir, "page.tsx")), `no page for ${route}`).toBe(true);
    }
  });

  it("precaches assets that exist", () => {
    const assets: string[] = JSON.parse(sw.match(/const CORE_ASSETS = (\[[^\]]*\])/)![1]!.replace(/'/g, '"'));
    for (const asset of assets) {
      // The manifest is generated by a route rather than sitting in public/.
      if (asset === "/manifest.webmanifest") {
        expect(existsSync(join(root, "src/app/manifest.ts"))).toBe(true);
        continue;
      }
      expect(existsSync(join(root, "public", asset)), `missing ${asset}`).toBe(true);
    }
  });

  it("claims clients so the first visit is protected, without hijacking an open page", () => {
    // clients.claim lets the worker start caching during the first visit.
    // skipWaiting would swap the worker under a page that is already running
    // and can leave it requesting chunks the new cache no longer has.
    expect(sw).toContain("clients.claim()");
    expect(sw).not.toContain("skipWaiting");
  });

  it("serves navigations network first, so a deploy is picked up while online", () => {
    expect(sw).toMatch(/request\.mode === "navigate"[\s\S]{0,80}networkFirst/);
  });

  it("never lets a fetch handler reject, which would surface as a network error", () => {
    for (const fn of ["cacheFirst", "staleWhileRevalidate", "networkFirst"]) {
      const body = sw.slice(sw.indexOf(`async function ${fn}(`));
      expect(body.slice(0, body.indexOf("\n}\n")), `${fn} has no failure path`).toMatch(/catch/);
    }
  });
});
